apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
      product: k6
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
        product: k6
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
        - name: k6load
          image: hrexed/xk6-dynatrace-test:0.4
          imagePullPolicy: Always
          args: ["-u", "200", "-d", "2h"]
          env:
            - name: FRONTEND_ADDR
              value: "keda.IP_TO_REPLACE.nip.io"
            - name: K6_DYNATRACE_URL
              valueFrom:
                secretKeyRef:
                  name: k6dynatrace
                  key: URL
            - name: K6_DYNATRACE_APITOKEN
              valueFrom:
                secretKeyRef:
                  name: k6dynatrace
                  key: APITOKEN
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi